### ISSUE TITLE
Unrecognized time zone identifier: "Europe/Kyiv"

### ISSUE THREAD

**Issue by cawa-93** [electerious/Ackee#343]
**🐞 Describe the bug**

On live demo I got this error:
```
unrecognized time zone identifier: "Europe/Kyiv"
```

**📚 To Reproduce**

1. Open demo
2. Try to Sign in

**💡 Expected behavior**

Just normaly work

**🖼️ Screenshots**

![зображення](https://user-images.githubusercontent.com/1662812/191103676-8f163bf5-2486-47ba-b9b6-428f53ae91a2.png)

**⚙️ Environment**
Live demo from README 🤷‍♂️
Browser: Firefox Developer edition v105.0b9 

**📋 Additional context**

In my opinion it may be related to recently renaming timezone Europe/Kiev to Europe/Kyiv

https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html

**Comment by electerious** [comment]
Thanks for letting me know!

> In my opinion it may be related to recently renaming timezone Europe/Kiev to Europe/Kyiv

I think that's the problem. I'm using `date-fns-tz` to work with timezones. A new version of the package might already support Europe/Kiev. A PR is welcome!

**Comment by cawa-93** [comment]
Regarding to https://github.com/marnusw/date-fns-tz/issues/120#issuecomment-828365540 it may be caused by mismatched nodejs timezones and browser timezones.

In firefox v105.0b9:
```js
> Intl.DateTimeFormat().resolvedOptions().timeZone 
< 'Europe/Kyiv'
```

In edge v105.0.1343.42:
```js
> Intl.DateTimeFormat().resolvedOptions().timeZone 
< 'Europe/Kiev'
```


But in node v18.8.0
```node
> new Intl.DateTimeFormat('en-US', {timeZone: 'Europe/Kyiv'}).format(Date.now())
Uncaught RangeError: Invalid time zone specified: Europe/Kyiv
    at new DateTimeFormat (<anonymous>)
```
```node
> new Intl.DateTimeFormat('en-US', {timeZone: 'Europe/Kiev'}).format(Date.now())
'9/20/2022'
```

Node already updated
https://github.com/nodejs/node/issues/44333

**Comment by cawa-93** [comment]
Confirm. In node 18.9.0 both timezone works. 
```js
> new Intl.DateTimeFormat('en-US', {timeZone: 'Europe/Kyiv'}).format(Date.now())
'9/20/2022'
> new Intl.DateTimeFormat('en-US', {timeZone: 'Europe/Kiev'}).format(Date.now())
'9/20/2022'
```

Therefore, I assume that updating the node on the demo server should solve this problem

**Comment by electerious** [comment]
I've updated `date-fns-tz` with Ackee 3.4.2. Can you check if the bug has been fixed?

**Comment by cawa-93** [comment]
Yeap. Still not working in firefox 109.0b3 on windows 10

**Comment by mks-h** [comment]
This is still an issue

**Comment by dmitrylen-fieldpulse** [comment]
use 
```
const isTimeZoneSupported = (tz: string): boolean => {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: tz });
    return true;
  } catch (e) {
    return false;
  }
};
```

**Comment by electerious** [comment]
The next version will require Node.js 22, which should fix the problem.

**Comment by dmitrylen-fieldpulse** [comment]
@electerious , The issue happens not only in Node, but on Mobile Android Chrome browser also

**Comment by electerious** [comment]
Node.js has been updated in the latest release. A PR is welcome when the issue is still present.

**Comment by bpavuk** [comment]
yup, it's still present. latest Zen Browser (a Firefox fork; receives platform updates in a timely fashion)
